version: "3.9"

services:

  traefik:
    image: traefik:v2.9
    container_name: "traefik"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ./traefik:/etc/traefik

  whoami:
    image: traefik/whoami
    container_name: "whoami"
    restart: "unless-stopped"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"
  
  flutter-app:
    image: testing-flutter/app:1.0.0_1
    container_name: "testing-flutter-app"
    restart: "unless-stopped"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flutter-app.rule=Host(`app.localhost`)"
      - "traefik.http.routers.flutter-app.entrypoints=web"

  prometheus:
    image: prom/prometheus:v2.37.6
    container_name: "prometheus"
    volumes: 
      - ./prometheus:/etc/prometheus
      - ./prometheus/data:/prometheus/data
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
      - "--storage.tsdb.path=/prometheus/data"
      - "--storage.tsdb.retention.time=15d"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.localhost`)"
      - "traefik.http.routers.prometheus.entrypoints=web"

  grafana: 
    image: grafana/grafana-oss:9.3.6
    container_name: grafana
    volumes:
      - ./grafana/data:/var/lib/graphana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.localhost`)"
      - "traefik.http.routers.grafana.entrypoints=web"
