apiVersion: v1
kind: Service
metadata:
  name: flutter-app-service
  namespace: testing-flutter

spec:
  type: ClusterIP
  ports:
    - name: web
      port: 80
      targetPort: web

  selector:
    app: flutter-app